openapi: 3.0.0
info:
  title: Platform API Documentation
  description: request api
  version: 1.0.0
servers:
  -url: http://platform-backend-dev.ap-northeast-1.elasticbeanstalk.com
  description: base url
tags:
  - name: basic
  - name: users
paths:
  /signup:
    post:
      tags:
        - basic
      summary: register a new user
      requestBody:
        content:
          application/json:
            schema:
              name:
                type: string
                example: user1 
              email:
                type: string
                example: user1@example.com
              password:
                type: string
                example: 12345678
              passwordCheck:
                type: string
                example: 12345678
      responses:
        '200':
        description: successful operation
        content:
          application/json:
            schema:
              
  /signin:
    post:
    summary: login a user
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/requestBodies/signin'
